flasher/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'notecard.views.list_decks', name='index'),
    url(r'^decks/$', 'notecard.views.list_decks', name='decks'),
    url(r'^decks/(?P<deck_id>\d+)/$', 'notecard.views.list_cards_in_deck', name='deck_details'),
    url(r'^cards/(?P<card_id>\d+)/$', 'notecard.views.notecard_details', name='card_details'),
    url(r'^decks/new/$', 'notecard.views.create_deck', name='create_deck'),
    url(r'^cards/new/(?P<deck_id>\d+)/$', 'notecard.views.create_card', name='create_card'),
    # url(r'^flasher/', include('flasher.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^accounts/login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout_then_login', name='logout'),
)

notecard/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

class Notecard(models.Model):
    owner = models.ForeignKey(User)
    deck = models.ManyToManyField("Deck")
    front = models.TextField()
    back = models.TextField()
    name = models.CharField(max_length=100)
    learned = models.BooleanField(default=False)
    times_reviewed = models.IntegerField(default=0)
    times_right = models.IntegerField(default=0)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('card_details',
                       args=[self.id, ]
                       )


class Deck(models.Model):
    owner = models.ForeignKey(User)
    name = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('deck_details',
                       args=[self.id, ]
                       )

notecard/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from notecard.models import Deck
from notecard.models import Notecard
from django.shortcuts import redirect
from django.core.urlresolvers import reverse


@login_required
def index(request):
    data = {
        'foo': 'hello world'
    }

    return render_to_response('notecard/index.html',
                              data,
                              context_instance=RequestContext(request)
                              )


@login_required
def list_decks(request):
    decks = Deck.objects.filter(owner=request.user)
    data = {
        'decks': decks,
    }
    return render_to_response('notecard/list_decks.html',
                              data,
                              context_instance=RequestContext(request)
                              )


@login_required
def list_cards_in_deck(request, deck_id):
    cards = Notecard.objects.filter(deck=deck_id)
    data = {
        'cards': cards,
        'deck_id': deck_id
    }
    return render_to_response('notecard/list_cards_in_deck.html',
                              data,
                              context_instance=RequestContext(request)
                              )


@login_required
def notecard_details(request, card_id):
    card = Notecard.objects.get(pk=card_id)
    data = {
        'card': card
    }
    return render_to_response('notecard/view_card.html',
                              data,
                              context_instance=RequestContext(request)
                              )


@login_required
def create_card(request, deck_id):
    deck_object = Deck.objects.get(pk=deck_id)
    if request.POST:
        card = Notecard()
        card.name = request.POST['name']
        card.owner = request.user
        card.front = request.POST['front']
        card.back = request.POST['back']
        card.save()
        card.deck.add(deck_object)
    return redirect(deck_object.get_absolute_url())


@login_required
def create_deck(request):
    if request.POST:
        deck = Deck()
        deck.owner = request.user
        deck.name = request.POST['name']
        deck.save()
    return redirect(reverse('decks'))

@login_required    
def delete_card(request,card_id):
    card = Notecard.objects.get(pk=request.POST['card_id']).delete()
    return render_to_response("notecard/list_decks",
                        context_instance=RequestContext(request)
                        )
@login_required
def edit_deck(request):
    deck = Deck.objects.get(pk=request.POST['deck_id'])        
    deck.name = request.POST['name']
    deck.save()
    return redirect(reverse('decks'))



@login_required
def delete_deck(request,deck_id):
    deck = Deck.objects.get(pk=request.POST['deck_id']).delete()
    return render_to_response("notecard/list_decks",
                        context_instance=RequestContext(request)
                        )
@login_required
def modify_card(request):
    """
    This code retreives cards infromation then updates the card
    """
    card = Notecard.objects.get(pk=request.POST['card_id'])
    if "name" in request POST:
        card.name = request.POST['name']
    if "front" in request POST:
        card.name = request.POST['front']
    if "back" in request POST:
        card.name = request.POST['back']
    if "deck" in request POST:
        deck_ids = request.POST['deck'].split(",")
        for _id in deck_ids:
            card.decks.add(Deck.objects.get(pk=_id)
    card.save()
    return render_to_response("notecard/deck_list",
                            context_instance=RequestContext(request)
                            )
    



    

notecard/templates/base.html
<!doctype html>
<html>
<head>
    <title>Notecard app!</title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap-responsive.min.css">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" ></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    <style>
        body { padding-top: 40px;}
        
    </style>
    {% block extra_head %}

    {% endblock %}
</head>

<body>
    {% block navbar %}
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="/">Notecards</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              {% if user.is_authenticated %}
                <li class="">
                    <a href="/decks/">Decks</a>
                </li>
                <li class="">
                    <a href="/accounts/logout/">Logout</a>
                </li>
              {% else %}
                <li class="">
                    <a href="/accounts/login/">Login</a>
                </li>
              {% endif %}
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    {% endblock %}

    <div class="container">
        <div class="row">
            <div class="span12">
                <!-- <h1>Welcome!</h1> -->
            </div>
        </div>
        <div class="row">
            

            <div class="span8 offset2">
                {% block content %}

                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

notecard/templates/notecard/index.html
{% extends 'base.html' %}

{% block sidebar %}
<ul>
    <li>Make a deck</li>
    <li>List decks</li>
    <li>Make a card</li>
</ul>
{% endblock %}


{% block content %}
This could be a list of decks
{% endblock %}

notecard/templates/notecard/list_cards_in_deck.html
{% extends 'base.html' %}

{% block sidebar %}

{% endblock %}


{% block content %}
<h1>Cards</h1>
    <a href="#newCard" role="button" class="btn btn-success" data-toggle="modal">New</a>
    <button class="btn">Play All</button>
    <button class="btn">Play Learned</button>
    <button class="btn">Play Unlearned</button>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Learned</th>
            <th>Times Right</th>
            <th>Times Reviewed</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        {% for card in cards %}
        <tr>
            <td><a href="{{card.get_absolute_url}}">{{card}}</a></td>
            <td>{{card.learned}}</td>
            <td>{{card.times_reviewed}}</td>
            <td>{{card.times_right}}</td>
            <td>
                <button class="btn btn-primary" >Share</button>
                <button class="btn btn-info" ><i class="icon-align-justify"></i></button>
                <button class="btn btn-danger"><i class="icon-trash"></i></button>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<div id="newCard" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="newCardLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="newCardLabel">Modal header</h3>
  </div>
  <div class="modal-body">
    <form class="form-horizontal" method="POST" action="{% url 'create_card' deck_id %}">
        {% csrf_token %}
      <div class="control-group">
        <label class="control-label" for="inputEmail">Name</label>
        <div class="controls">
          <input type="text" id="name" name="name" placeholder="Name">
        </div>
      </div>
      <div class="control-group">
        <label class="control-label" for="inputEmail">Front</label>
        <div class="controls">
          <textarea id="front" name="front" placeholder="front"></textarea>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label" for="inputEmail">Back</label>
        <div class="controls">
            <textarea id="back" name="back" placeholder="back"></textarea>
          
        </div>
      </div>
      <div class="control-group">
        <div class="controls">
          <button type="submit" class="btn">Save</button>
        </div>
      </div>
    </form>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>


{% endblock %}

notecard/templates/notecard/list_decks.html
{% extends 'base.html' %}

{% block sidebar %}

{% endblock %}


{% block content %}
<h1>Decks</h1>
<a href="#newDeck" role="button" class="btn btn-success" data-toggle="modal">New</a>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th># cards</th>
            <th>Created</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        {% for deck in decks %}
        <tr>
            <td><a href="{{deck.get_absolute_url}}">{{deck}}</a></td>
            <td>{{deck.notecard_set.all|length}}</td>
            <td>{{deck.date_created}}</td>
            <td>
                <button class="btn btn-primary" >Share</button>
                <button class="btn btn-info" ><i class="icon-align-justify"></i></button>
                <button class="btn btn-danger"><i class="icon-trash"></i></button>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>


<div id="newDeck" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="newDeckLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="newDeckLabel">Modal header</h3>
  </div>
  <div class="modal-body">
    <form class="form-horizontal" method="POST" action="{% url 'create_deck' %}">
        {% csrf_token %}
      <div class="control-group">
        <label class="control-label" for="inputEmail">Name</label>
        <div class="controls">
          <input type="text" id="name" name="name" placeholder="Name">
        </div>
      </div>
      <div class="control-group">
        <div class="controls">
          <button type="submit" class="btn">Save</button>
        </div>
      </div>
    </form>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>


{% endblock %}

notecard/templates/notecard/view_card.html
{% extends 'base.html' %}

{% block sidebar %}
<ul>
    <li>Make a deck</li>
    <li>List decks</li>
    <li>Make a card</li>
</ul>
{% endblock %}


{% block content %}

<h1><a href="{{card.get_absolute_url}}">{{card}}</a></h1>

{% endblock %}

templates/base.html
<!doctype html>
<html>
<head>
    <title>Notecard app!</title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap-responsive.min.css">
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    <style>
        .row div{ background-color:#eee;}
    </style>
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="span12"></div>
        </div>
        <div class="row">
            <div class="span6"></div>
            <div class="span6"></div>
        </div>
        <div class="row">
            <div class="span4"></div>
            <div class="span4"></div>
            <div class="span4"></div>
        </div>
        <div class="row">
            <div class="span3"></div>
            <div class="span3"></div>
            <div class="span3"></div>
            <div class="span3"></div>
        </div>
        <div class="row">
            <div class="span2"></div>
            <div class="span2"></div>
            <div class="span2"></div>
            <div class="span2"></div>
            <div class="span2"></div>
            <div class="span2"></div>
        </div>
    </div>
</body>
</html>